apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: production
  labels:
    app: demo-app
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
      environment: production
  template:
    metadata:
      labels:
        app: demo-app
        environment: production
    spec:
      containers:
      - name: demo-app
        image: REGISTRY_URL/demo-app:TAG
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5